config/routes.rb
Likestatus::Application.routes.draw do
  resources :products


  get "dashboard/index"

  authenticated :user do
    root :to => 'dashboard#index'
  end


  root :to => "home#index"
  devise_for :users
  resources :users
  post 'status_update' => "users#status_update"
  match 'status_like/:id' => "users#status_like", :as => "status_like"
  get 'unlike_status/:id' => "users#unlike_status", :as => "unlike_status"

  get 'collection/:id' => "collection#show", :as => :product_collection
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
  	@user = current_user
  	@products = Product.all
  end
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/views/dashboard/index.html.haml
%h1
	Welcome 
	= @user.name
.row-fluid.show-grid
	.span9
		.row-fluid.show-grid
			- @products.first(3).each do |product|
				.span3.product-bg
					= link_to product.name, product_path(product.id), :class=> "product-link"
					.asdf
						= link_to "<i class = 'icon-plus'></i>".html_safe, product_collection_path(product.id)
						= link_to "<i class = 'icon-star'></i>".html_safe
						= link_to "<i class = 'icon-add-to-list', style='background-position:inherit;'></i>".html_safe


/ <ul class="nav span12">
/   <li class="active span3">
/     <a href="#">Home</a>
/   </li>
/   <li class="span3"><a href="#">Link</a></li>
/   <li class="span3"><a href="#">Link</a></li>
/   <li class="span3"><a href="#">Link</a></li>
/ </ul>		